### ISSUE TITLE
关于训练的两个阶段的问题

### ISSUE THREAD

**Issue by myname4423** [Roxanne-Wang/DPPN-GZSL#1]
作者您好！冒昧打扰您，请问为什么训练代码中有的数据集（如cub和apy）用两个stage，两个stage之间的差别好像只有batchsize和is_fix的参数的区别，请问这样训练的目的是什么呢？

**Comment by Roxanne-Wang** [comment]
你好，我们的两阶段训练，第一阶段是固定backbone训练其他部分，第二阶段放开backbone进行end2end训练，这样可以提升最终结果。
